# Welcome to NumPy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,6]], np.int64)

In [3]:
myarr[0, 1]

np.int64(6)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0, 1] = 45

In [9]:
 myarr

array([[ 3, 45, 32,  6]])

# Array creation: Conversion from other Python Structures

In [10]:
listarray = np.array ([[1,2,3], [4,5,6], [7,8,9]])

In [12]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarray.dtype

dtype('int64')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({34,23,33})

array({33, 34, 23}, dtype=object)

In [17]:
zeros = np.zeros((3,9))

In [18]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(3, 9)

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
lspace = np.linspace(1,5,4)

In [46]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [35]:
emp = np.empty((4,6))

In [36]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061414e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.51319826e-306, 1.11261570e-306,
        1.02359645e-306, 7.56591659e-307, 1.42410974e-306]])

In [47]:
emp_like = np.empty_like(lspace)

In [48]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [41]:
ide = np.identity(45)

In [42]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [43]:
ide.shape

(45, 45)

In [49]:
arr = np.arange(99)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [51]:
arr = arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [54]:
arr = arr.ravel()

In [55]:
arr.shape

(99,)

In [56]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [57]:
ar = np.array(x)

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [59]:
ar.sum(axis=0)

array([12,  8,  9])

In [60]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [63]:
ar.T 

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [64]:
ar.flat

In [65]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [67]:
ar.ndim

2

In [68]:
ar.size

9

In [69]:
ar.nbytes

72

In [75]:
one = np.array([1,3,4,634,2,34,23,100])

In [76]:
one.argmax()

np.int64(3)

In [73]:
one

array([  1,   3,   4, 634,   2])

In [74]:
one.argmin()

np.int64(0)

In [77]:
one.argsort()

array([0, 4, 1, 2, 6, 5, 7, 3])

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [80]:
ar.argmin()

np.int64(8)

In [81]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [82]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [85]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [86]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [87]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [88]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [89]:
[324, 34] + [34, 546]

[324, 34, 34, 546]

In [90]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [91]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [92]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [93]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [95]:
ar % ar2

C:\Users\simak\AppData\Local\Temp\ipykernel_23372\3841496730.py:1: RuntimeWarning: divide by zero encountered in remainder
  ar % ar2


array([[0, 0, 0],
       [0, 0, 0],
       [7, 0, 0]])

In [96]:
ar.sum()

np.int64(29)

In [98]:
ar.min()

np.int64(0)

In [99]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [100]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [101]:
type(np.where(ar>5))

tuple

In [102]:
np.count_nonzero(ar)

np.int64(8)

In [104]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [105]:
ar[1,2] = 0

In [106]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [107]:
import sys

In [109]:
py_ar = [0,4,55,2] 

In [110]:
np_ar = np.array(py_ar)

In [111]:
sys.getsizeof(1) * len(py_ar)

112

In [113]:
np_ar.itemsize * np_ar.size

32